@api = http://localhost:7071/api
@hostkey = f




### Run Import
POST {{api}}/import/run?code={{hostkey}}&datefrom=2017-01-01&dateto=2018-08-01&bggusername=Aredhel


### Run Import with configured params
POST {{api}}/import/run
x-functions-key: {{hostkey}}
